name: de4js
title: de4js
description: JavaScript Deobfuscator and Unpacker
version: 1.12.0
author: Smart Tech Mukesh
author_email: smarttechmukesh@gmail.com
url: https://wwww.smarttechmukesh.online
baseurl: /de4js
repository: smarttechmukesh/de4js
license: MIT

theme: jekyll-theme-hacker
show_downloads: false
google_analytics: UA-106940288-1
sass:
  style: compressed

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "package.json",
    "package-lock.json",
    "Dockerfile",
    "docker-compose.yml",
    "docker-entrypoint.sh",
    "workbox-config.js"
  ]
incremental: false

environment: production
